// Define the structure of a JWT token payload
export interface AuthToken {
    id: number; // User ID encoded in the token
    iat: number; // Issued at timestamp (generated by the JWT library)
    exp: number; // Expiration timestamp
}